# Generated by Django 4.0.3 on 2022-03-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='no_of_days_members',
            new_name='no_of_members',
        ),
    ]
