# Generated by Django 4.0.3 on 2022-03-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_no_of_days_members_task_no_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.IntegerField(null=True),
        ),
    ]
